let p = 100000007

let mul_p x y = (x*y) % p

let add_p x y = (x+y) % p

let sum_p = foldl add_p 0

let scanl f =
  let rec scanl_f y0 xs =
    match xs with
    | Nil -> Nil
    | Cons x xs ->
      let y0 = f y0 x in
      Cons y0 (scanl_f y0 xs)
  in
  scanl_f

let rec sols =
  Cons 1
    (map (fun xs -> sum_p (zip_with mul_p sols xs))
      (scanl (fun xs x -> Cons x xs) Nil sols))

let main = print (nth sols 2000 % p)
