import std/prelude

val prime : Int
let prime = 1000000*1000000+39

val add_mod_prime : Int -> Int -> Int
let add_mod_prime x y =
  let z = x+y in
  if z < prime then z else z - prime

val fibs0 : List Int
val fibs1 : List Int
let rec fibs0 = Cons 0 fibs1
and     fibs1 = Cons 1 (zip_with add_mod_prime fibs0 fibs1)

val main : IO Unit
let main =
  input
  >>= fun n ->
  print (nth fibs0 n)
