import std/prelude

val insert : Int -> List Int -> List Int
let rec insert y xs =
  match xs with
  | Nil -> Cons y Nil
  | Cons x xs' ->
    if y <= x then
      Cons y xs
    else
      Cons x (insert y xs')

val isort : List Int -> List Int
let rec isort xs =
  match xs with
  | Nil -> Nil
  | Cons x xs -> insert x (isort xs)

val main : IO Unit
let main =
  input
  >>= fun n ->
  sequence_io (replicate n input)
  >>= fun xs ->
  iter_io print (isort xs)
