val when : Bool -> IO Unit -> IO Unit
let when p m = if p then m else return Unit

val count_down : Int -> IO Unit
let rec count_down k = when (k >= 0) (print k; count_down (k-1))

val repeat_m : Int -> IO Unit -> IO Unit
let rec repeat_m k m = when (k > 0) (m; repeat_m (k-1) m)

val main : IO Unit
let main = repeat_m 3 (count_down 2)
