import std2/io

count_down : Int -> IO Unit
count_down k = when (k >= 0) (print k; count_down (k-1))

repeat : (Monad m) => Int -> m Unit -> m Unit
repeat k m = when (k > 0) (m; repeat (k-1) m)

main : IO Unit
main =
  input
  >>= fun k ->
  input
  >>= fun n ->
  repeat k (count_down n)
