let when p m = if p then m else return Unit

let rec count_down k = when (k >= 0) (print k; count_down (k-1))

let rec repeat_m k m = when (k > 0) (m; repeat_m (k-1) m)

let main = repeat_m 3 (count_down 2)
