val repeat : List a -> List a
let repeat xs =
  let rec ys = append xs ys in
  ys

val psums : List Int -> List Int
let psums =
  let rec psums0 n xs =
    match xs with
    | Nil -> Nil
    | Cons x xs ->
      let y = x + n in
      Cons y (psums0 y xs)
  in
  psums0 0

val filter : (a -> Bool) -> List a -> List a
let filter p =
  let rec filter_p xs =
    match xs with
    | Nil -> Nil
    | Cons x xs ->
      let ys = filter_p xs in
      if p x then Cons x ys else ys
  in
  filter_p

val sieve : List Int -> List Int
let rec sieve ks =
  match ks with
  | Nil -> abort
  | Cons p ks -> Cons p (sieve (filter (fun k -> k % p != 0) ks))

val primes : List Int
let primes = Cons 2 (Cons 3 (sieve (psums (Cons 5 (repeat (Cons 2 (Cons 4 Nil)))))))

val main : IO Unit
let main =
  input
  >>= fun n ->
  print (nth primes n)
