val qsort : List Int -> List Int
let rec qsort xs =
  match xs with
  | Nil -> Nil
  | Cons x xs ->
    match partition (fun y -> y < x) xs with
    | Pair ys zs -> append (qsort ys) (Cons x (qsort zs))

val main : IO Unit
let main =
  input
  >>= fun n ->
  sequence_io (replicate n input)
  >>= fun xs ->
  iter_io print (qsort xs)
