import std2/prelude

gen :: (a -> a) -> a -> List a
gen f x = Cons x (gen f (f x))

main :: IO Unit
main =
  input
  >>= \n ->
  print n;
  traverse_ print (take n (gen (\x -> (91*x) % 1000000007) 1))
