import std/prelude
import std/tree

tsort : List Int -> List Int
tsort xs = in_order (foldl (fun t x -> insert_tree x t) Leaf xs)

main : IO Unit
main =
  input
  >>= fun n ->
  sequence_io (replicate n input)
  >>= fun xs ->
  iter_io print (tsort xs)
