import std2/prelude

fst : Pair a b -> a
fst p =
  match p with
  | Pair x _ -> x

snd : Pair a b -> b
snd p =
  match p with
  | Pair _ y -> y

main : IO Unit
main =
  input
  >>= fun x ->
  input
  >>= fun y ->
  let p = Pair x y in
  print (fst p);
  print (snd p)
