import std2/prelude

fst :: Pair a b -> a
fst p =
  case p of
  | Pair x _ -> x

snd :: Pair a b -> b
snd p =
  case p of
  | Pair _ y -> y

main :: IO Unit
main =
  input
  >>= \x ->
  input
  >>= \y ->
  let p = Pair x y in
  print (fst p);
  print (snd p)
