# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

branches:
  only:
  - master

os:
- linux
- osx

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/.local

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
    - libgmp-dev
  homebrew:
    packages:
    - gmp

before_install:
# Set up stack and nasm
- ./.travis/setup.sh
- export PATH=$HOME/.local/bin:$PATH
# Install hlint
- stack -j1 --no-terminal --install-ghc build hlint

install:
# Build dependencies
- stack -j1 --no-terminal test --only-dependencies

script:
# Run hlint
- stack exec hlint -- --git
# Build the package, its tests, and its docs and run the tests
- stack -j1 --no-terminal test --pedantic
