name: pukeko
version: 0.0.1
synopsis: "A toy compiler based on SPJ's book \"The Implementation of Functional Programming Languages\""
description: Please see README.md
category: Compilers/Interpreters
author: Martin Huschenbett <martin.huschenbett@posteo.me>
copyright: 2017 Martin Huschenbett
license: BSD3
github: hurryabit/pukeko

dependencies:
- base
default-extensions:
- DataKinds
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MonadFailDesugaring
- NamedFieldPuns
- OverloadedStrings
- PartialTypeSignatures
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeFamilies
ghc-options:
- -Wall
- -Werror
- -Wno-missing-signatures
- -Wno-name-shadowing
- -Wno-partial-type-signatures

library:
  source-dirs: src
  exposed-modules:
  - Pukeko
  - Pukeko.GMachine.Compiler
  - Pukeko.GMachine.NASM
  - Pukeko.GMachine.PeepHole
  - Pukeko.Language.Parser
  - Pukeko.Pretty
  dependencies:
  - array
  - call-stack
  - containers
  - fclabels
  - lens
  - monad-st
  - mtl
  - parsec
  - pretty
  - tagged
  - transformers
  - vector

executables:
  pukeko:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - pukeko
    - filepath
    - mtl
    - optparse-applicative

tests:
  reject:
    main: Reject.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-core
    - HUnit
    - parsec
    - pukeko

  examples:
    main: Examples.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
    - hspec
    - HUnit
    - process
    - QuickCheck
