name: pukeko
version: 0.0.2
synopsis: "A toy compiler based on SPJ's book \"The Implementation of Functional Programming Languages\""
description: Please see README.md
category: Compilers/Interpreters
author: Martin Huschenbett <martin.huschenbett@posteo.me>
copyright: 2017-2020 Martin Huschenbett
license: BSD3
github: hurryabit/pukeko

dependencies:
- base
default-extensions:
- ConstraintKinds
- DataKinds
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns
ghc-options:
- -Wall
- -Werror
- -O0

library:
  source-dirs: src
  exposed-modules:
  - Pukeko.AST.Name
  - Pukeko.BackEnd
  - Pukeko.FrontEnd
  - Pukeko.FrontEnd.Parser
  - Pukeko.MiddleEnd
  - Pukeko.MiddleEnd.CallGraph
  - Pukeko.Prelude
  - Pukeko.Pretty
  dependencies:
  - aeson
  - aeson-pretty
  - array
  - bound
  - bytestring
  - call-stack
  - containers
  - deriving-compat
  - dlist
  - extra
  - filepath
  - freer-simple
  - lens
  - megaparsec
  - mtl
  - natural-transformation
  - parser-combinators
  - pretty
  - profunctors
  - safe
  - tagged
  - text
  - transformers
  - union-find
  - vector

executables:
  pukeko:
    main: Main
    other-modules: []
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - aeson-pretty
    - bytestring
    - pukeko
    - filepath
    - mtl
    - optparse-applicative
    - text

tests:
  golden:
    main: Golden
    other-modules: []
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - extra
    - filepath
    - pukeko
    - tasty
    - tasty-golden

  run-examples:
    main: RunExamples
    other-modules: []
    source-dirs: test
    ghc-options:
    - -Wno-missing-signatures
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
    - filepath
    - hspec
    - HUnit
    - process
    - pukeko
    - QuickCheck
