-- Booleans
type Bool =
  | False
  | True

val not : Bool -> Bool
let not x = if x then False else True

val (&&) : Bool -> Bool -> Bool
let (&&) x y = if x then y else False

val (||) : Bool -> Bool -> Bool
let (||) x y = if x then True else y
