import std/bool

-- Integers
type Int

neg : Int -> Int
external neg = "neg"

(+) : Int -> Int -> Int
external (+) = "add"

(-) : Int -> Int -> Int
external (-) = "sub"

(*) : Int -> Int -> Int
external (*) = "mul"

(/) : Int -> Int -> Int
external (/) = "div"

(%) : Int -> Int -> Int
external (%) = "mod"

(==) : Int -> Int -> Bool
external (==) = "eq"

(!=) : Int -> Int -> Bool
external (!=) = "ne"

(<) : Int -> Int -> Bool
external (<) = "lt"

(<=) : Int -> Int -> Bool
external (<=) = "le"

(>=) : Int -> Int -> Bool
external (>=) = "ge"

(>) : Int -> Int -> Bool
external (>) = "gt"
