import std/basic
import std/int
import std/list

-- IO
type IO a

return : a -> IO a
external return = "return"

print : Int -> IO Unit
external print = "print"

input : IO Int
external input = "input"

(>>=) : IO a -> (a -> IO b) -> IO b
external (>>=) = "bind"

(;) : IO Unit -> IO a -> IO a
(;) m1 m2 = m1 >>= fun x -> m2

sequence_io : List (IO a) -> IO (List a)
sequence_io ms =
  match ms with
  | Nil -> return Nil
  | Cons m ms ->
    m
    >>= fun x ->
    sequence_io ms
    >>= fun xs ->
    return (Cons x xs)

iter_io : (a -> IO Unit) -> List a -> IO Unit
iter_io f = foldr (fun x m -> f x; m) (return Unit)

print_list : List Int -> IO Unit
print_list = iter_io print
