import std/int
import std/list

-- Binary trees
type Tree a =
  | Leaf
  | Branch (Tree a) a (Tree a)

insert_tree : Int -> Tree Int -> Tree Int
insert_tree x t =
  match t with
  | Leaf -> Branch Leaf x Leaf
  | Branch l y r ->
    if x <= y then
      Branch (insert_tree x l) y r
    else
      Branch l y (insert_tree x r)

in_order : Tree a -> List a
in_order t =
  match t with
  | Leaf -> Nil
  | Branch l x r -> append (in_order l) (Cons x (in_order r))
