{-# LANGUAGE DataKinds #-}
-- | AST generated by the introduction of de Bruijn indices.
module Pukeko.Language.TypeResolver.AST
  ( TCon
  , DCon
  , Module
  , TopLevel (..)
  , Defn
  , Expr
  , Altn
  , Patn
  ) where

import qualified Data.Vector.Sized as Vec

import           Pukeko.Pos
import           Pukeko.Language.AST.Std
import qualified Pukeko.Language.Ident    as Id
import qualified Pukeko.Language.Type     as Ty

data TYPERESOLVER

type TCon = Ty.ADT Id.TCon
type DCon = Ty.Constructor TCon

instance Stage TYPERESOLVER where
  type DConRef TYPERESOLVER = DCon
  type HasLam  TYPERESOLVER = 'True
  type HasMat  TYPERESOLVER = 'True

type Module = [TopLevel]

data TopLevel
  =           TypDef Pos [Ty.ADT TCon]
  |           Val    Pos Id.EVar (Ty.Type TCon Ty.Closed)
  | forall n. TopLet Pos (Vec.Vector n (Defn Id.EVar))
  | forall n. TopRec Pos (Vec.Vector n (Defn (FinScope n Id.EVar)))
  |           Asm    Pos Id.EVar String

type Defn = StdDefn TYPERESOLVER
type Expr = StdExpr TYPERESOLVER
type Altn = StdAltn TYPERESOLVER
type Patn = StdPatn TYPERESOLVER
