{-# LANGUAGE DataKinds #-}
-- | AST generated by the introduction of de Bruijn indices.
module Pukeko.Language.TypeResolver.AST
  ( Module
  , TopLevel
  , Defn
  , Expr
  , Altn
  , Patn
  ) where

import           Pukeko.Language.AST.Std

data TYPERESOLVER

instance Stage TYPERESOLVER where
  type StageId TYPERESOLVER = 200

type Module = StdModule TYPERESOLVER
type TopLevel = StdTopLevel TYPERESOLVER
type Defn = StdDefn TYPERESOLVER
type Expr = StdExpr TYPERESOLVER
type Altn = StdAltn TYPERESOLVER
type Patn = StdPatn TYPERESOLVER
