add :: Int -> Int -> Int
external add = "add"

infix + add

g :: Int -> Int -> Int -> Int -> Int
g a b c d = a

f :: Int -> Int -> Int -> Int -> Int
f = \x -> \y1 y2 -> \z -> g x y1 y2 z

h :: Int -> Int
h x = x + x

main :: Int
main = f 1 2 3 (h 2)
