import std2/io
import std2/bag

tsort :: List Int -> List Int
tsort xs = to_list (foldl (\s x -> bag_insert x s) bag_empty xs)

main :: IO Unit
main =
  input
  >>= \n ->
  sequence (replicate n input)
  >>= \xs ->
  traverse_ print (tsort xs)
