{-# LANGUAGE DataKinds #-}
-- | AST generated by the introduction of de Bruijn indices.
module Pukeko.Language.Renamer.AST
  ( Module
  , TopLevel
  , Defn
  , Expr
  , Altn
  , Patn
  )
where

import           Pukeko.Language.AST.Std

data RENAMER

instance Stage RENAMER where
  type StageId RENAMER = 100

type Module = StdModule RENAMER
type TopLevel = StdTopLevel RENAMER
type Defn = StdDefn RENAMER
type Expr = StdExpr RENAMER
type Altn = StdAltn RENAMER
type Patn = StdPatn RENAMER
