-- Fundamental functions
abort : a
external abort = "abort"

-- Fundamental types
type Unit =
  | Unit

type Bool =
  | False
  | True

type Pair a b =
  | Pair a b

type Option a =
  | None
  | Some a

type Choice a b =
  | First a
  | Second b

-- Fundamental classes
class Eq a where (==) : a -> a -> Bool

(!=) : (Eq a) => a -> a -> Bool
(!=) x y = if x == y then False else True

-- Fundamental functions
id : a -> a
id x = x

(∘) : (b -> c) -> (a -> b) -> (a -> c)
(∘) f g x = f (g x)
