-- The IO monad
import std2/char
import std2/int
import std2/monad

type IO a

pure_io : a -> IO a
external pure_io = "return"

bind_io : IO a -> (a -> IO b) -> IO b
external bind_io = "bind"

instance Monad IO where
  pure = pure_io
  (>>=) = bind_io


print : Int -> IO Unit
external print = "print"

input : IO Int
external input = "input"

putChar : Char -> IO Unit
external putChar = "putc"

getCharRaw : IO Int
external getCharRaw = "getc"

getChar : IO (Option Char)
getChar =
  getCharRaw
  >>= fun n ->
  pure (if n < 0 then None else Some (chr n))
