-- The monad class and some useful functions for monads
import std2/basic
import std2/list

class Monad m where
  pure : a -> m a
  (>>=) : m a -> (a -> m b) -> m b

(;) : (Monad m) => m Unit -> m a -> m a
(;) m1 m2 = m1 >>= fun x -> m2

sequence : (Monad m) => List (m a) -> m (List a)
sequence ms =
  match ms with
  | Nil -> pure Nil
  | Cons m ms ->
      m
      >>= fun x ->
      sequence ms
      >>= fun xs ->
      pure (Cons x xs)

traverse_ : (Monad m, Foldable t) => (a -> m Unit) -> t a -> m Unit
traverse_ f = foldr (fun x m -> f x; m) (pure Unit)

when : (Monad m) => Bool -> m Unit -> m Unit
when p m = if p then m else pure Unit
