-- Operations and instances on pairs
import std2/basic

instance eqPair :: (Eq a, Eq b) => Eq (Pair a b) where
  eq x y =
    case x of
    | Pair x1 x2 ->
      case y of
      | Pair y1 y2 ->
        eq x1 y1 && eq x2 y2
